package entidades;
// Generated 09/09/2019 16:32:54 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "curso", schema = "public")
public class Curso implements java.io.Serializable {

	private long id;
	private long valor;
	private String url;
	private String nome;
	private int cdcurso;

	public Curso() {
	}

	public Curso(long valor, String url, String nome, int cdcurso) {
		this.valor = valor;
		this.url = url;
		this.nome = nome;
		this.cdcurso = cdcurso;
	}

	@Id @GeneratedValue (strategy=GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "valor", nullable = false)
	public long getValor() {
		return this.valor;
	}

	public void setValor(long valor) {
		this.valor = valor;
	}

	@Column(name = "url", nullable = false, length = 80)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "nome", nullable = false, length = 80)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cdcurso", nullable = false)
	public int getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(int cdcurso) {
		this.cdcurso = cdcurso;
	}

}
