package entidades;
// Generated 09/09/2019 16:32:54 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", schema = "public")
public class Login implements java.io.Serializable {

	private long cpf;
	private String senha;

	public Login() {
	}

	public Login(long cpf, String senha) {
		this.cpf = cpf;
		this.senha = senha;
	}

	@Id

	@Column(name = "cpf", unique = true, nullable = false)
	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	@Column(name = "senha", nullable = false, length = 40)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

}
