package entidades;
// Generated 09/09/2019 16:32:54 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PagamentoId generated by hbm2java
 */
@Embeddable
public class PagamentoId implements java.io.Serializable {

	private int cdcurso;
	private long cpf;

	public PagamentoId() {
	}

	public PagamentoId(int cdcurso, long cpf) {
		this.cdcurso = cdcurso;
		this.cpf = cpf;
	}

	@Column(name = "cdcurso", nullable = false)
	public int getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(int cdcurso) {
		this.cdcurso = cdcurso;
	}

	@Column(name = "cpf", nullable = false)
	public long getCpf() {
		return this.cpf;
	}

	public void setCpf(long cpf) {
		this.cpf = cpf;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PagamentoId))
			return false;
		PagamentoId castOther = (PagamentoId) other;

		return (this.getCdcurso() == castOther.getCdcurso()) && (this.getCpf() == castOther.getCpf());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCdcurso();
		result = 37 * result + (int) this.getCpf();
		return result;
	}

}
